[build]
builder = "NIXPACKS"
buildCommand = "cd .. && mvn clean install -DskipTests && cd visit-service && mvn clean package -DskipTests"

[deploy]
startCommand = "java -Dserver.port=$PORT -jar target/*.jar"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
