[build]
builder = "NIXPACKS"
buildCommand = "mvn clean install -DskipTests -f ../pom.xml && mvn clean package -DskipTests"

[deploy]
startCommand = "java -Dserver.port=$PORT -jar target/*.jar"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
