[phases.setup]
nixPkgs = ["maven", "jdk21"]

[phases.build]
cmds = [
  "mvn clean install -DskipTests",
  "cd client-service && mvn clean package -DskipTests"
]

[phases.install]
dependsOn = ["build"]
cmds = [
  "mkdir -p /app/output",
  "cp client-service/target/*.jar /app/output/app.jar"
]

[start]
cmd = "java -Dserver.port=$PORT -jar /app/output/app.jar"
