[phases.setup]
nixPkgs = ["maven", "jdk21"]

[phases.build]
cmds = [
  "mvn clean install -DskipTests",
  "cd client-service && mvn clean package -DskipTests",
  "mkdir -p target",
  "cp client-service/target/*.jar target/"
]

[start]
cmd = "java -Dserver.port=$PORT -jar target/*.jar"
